apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: image-intake-pipeline-prevail-2021
spec:
  params:
    - default: 'registry.access.redhat.com/ubi8/ubi:8.0'
      description: The URL of the image that we want to scan and import into the tools-images project.
      name: image-url
      type: string
    - default: "ubi:8.0"
      description: The name of image stream where the image will be imported.
      name: image-name
      type: string         
    - default: "UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL"
      description: The threshold where the trivy scan fill fail the pipeline.
      name: trivy-severity
      type: string        
  tasks:
    - name: scan-image
      taskRef:
        name: ibm-img-scan-trivy
      params:
      - name: image-url
        value: $(params.image-url)
      - name: scan-image
        value: "true"  
      - name: TRIVY_SEVERITY
        value: $(params.trivy-severity)
    - name: import-image
      taskRef:
        name: aot-mockup
      runAfter:
        -  scan-image

