apiVersion: v1
items:
- apiVersion: tekton.dev/v1alpha1
  kind: PipelineResource
  metadata:
    name: customer-source-fix-version
  spec:
    params:
    - name: revision
      value: fix-version
    - name: url
      value: https://github.com/kitty-catt/customer-ms-spring
    type: git
kind: List
