apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clone-2-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  #storageClassName: ibmc-file-retain-silver