apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-repo-pvc
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
#storageClassName: ibmc-file-gold-gid
#storageClassName: ibmc-file-retain-silver