apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iam-pvc
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  #storageClassName: ibmc-file-gold-gid