apiVersion: v1
kind: Secret
metadata:
  name: crc-creds-skopeo
  annotations:
    tekton.dev/docker-0: https://default-route-openshift-image-registry.apps-crc.testing/v2/
type: kubernetes.io/basic-auth
stringData:
  username: CRC_USER
  password: CRC_PASSWORD
