apiVersion: v1
kind: Secret
metadata:
  name: quay-creds-skopeo
  annotations:
    tekton.dev/docker-0: https://quay.io
type: kubernetes.io/basic-auth
stringData:
  username: QUAY_USER
  password: QUAY_PASSWORD
