apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: aot-maven
spec:
  params:
    - default:
        - package
      description: maven goals to run
      name: GOALS
      type: array
    - default: ''
      description: The Maven repository mirror url
      name: MAVEN_MIRROR_URL
      type: string
    - default: ''
      description: The username for the proxy server
      name: PROXY_USER
      type: string
    - default: ''
      description: The password for the proxy server
      name: PROXY_PASSWORD
      type: string
    - default: ''
      description: Port number for the proxy server
      name: PROXY_PORT
      type: string
    - default: ''
      description: Proxy server Host
      name: PROXY_HOST
      type: string
    - default: ''
      description: Non proxy server host
      name: PROXY_NON_PROXY_HOSTS
      type: string
    - default: http
      description: Protocol for the proxy ie http or https
      name: PROXY_PROTOCOL
      type: string
    - default: security
      description: the folder containing the module to build
      name: module
      type: string
    - default: 'kitchensink'
      name: git-repo-checkout-dir
    - name: pom-dir
      default: '.'      
  steps:
    - name: mvn-settings 
      image: 'registry.access.redhat.com/ubi8/ubi-minimal:latest'
      resources: {}
      script: |
        #!/usr/bin/env bash

        FILE=$(workspaces.maven-settings.path)/settings.xml

        if [[ -f "$FILE" ]]; then
            echo "running under $(id)"
            ls -lrt $FILE
            echo "$FILE exists."
            exit 0
        fi
        exit 1
    - name: mvn-version
      args:
        - '-v'
      command:
        - /usr/bin/mvn
      image: gcr.io/cloud-builders/mvn:3.5.0-jdk-8
      resources: {}
      workingDir: $(workspaces.source.path)/$(params.git-repo-checkout-dir)/$(params.pom-dir)
    - name: mvn-goals
      args:
        - '-s'
        - $(workspaces.maven-settings.path)/settings.xml
        - -Dmaven.repo.local=$(workspaces.maven-repo.path)
        - -e
        - $(params.GOALS)
      command:
        - /usr/bin/mvn
      image: gcr.io/cloud-builders/mvn
      resources: {}
      workingDir: $(workspaces.source.path)/$(params.git-repo-checkout-dir)/$(params.pom-dir)  
  workspaces:
    - name: source
    - name: maven-settings
    - name: maven-repo
