apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: aot-maven
spec:
  params:
    - default:
        - package
      description: maven goals to run
      name: GOALS
      type: array
    - default: ''
      description: The Maven repository mirror url
      name: MAVEN_MIRROR_URL
      type: string
    - default: ''
      description: The username for the proxy server
      name: PROXY_USER
      type: string
    - default: ''
      description: The password for the proxy server
      name: PROXY_PASSWORD
      type: string
    - default: ''
      description: Port number for the proxy server
      name: PROXY_PORT
      type: string
    - default: ''
      description: Proxy server Host
      name: PROXY_HOST
      type: string
    - default: ''
      description: Non proxy server host
      name: PROXY_NON_PROXY_HOSTS
      type: string
    - default: http
      description: Protocol for the proxy ie http or https
      name: PROXY_PROTOCOL
      type: string
    - default: security
      description: the folder containing the module to build
      name: module
      type: string
    - default: 'kitchensink'
      name: git-repo-checkout-dir
    - name: pom-dir
      default: '.'      
  steps:
    - image: image-registry.openshift-image-registry.svc.cluster.local:5000/tools-images/ubi-minimal:for-use
      name: mvn-settings-generation
      resources: {}
      script: >
        #!/usr/bin/env bash

        echo 'Generated $(workspaces.maven-settings.path)/settings.xml:' 

        rm -f $(workspaces.maven-settings.path)/settings.xml 

        cat > $(workspaces.maven-settings.path)/settings.xml <<EOF

        <settings>
          <servers>
            <server>
              <id>releases-repository</id>
              <username>admin</username>
              <password>admin123</password>
            </server>
            <server>
              <id>snapshots-repository</id>
              <username>admin</username>
              <password>admin123</password>
            </server>
            <server>
              <id>mirror.default</id>
              <username>admin</username>
              <password>admin123</password>
            </server>
            <server>
              <id>silver-platter</id>
              <username>aot-user</username>
              <password>ibm-prevail-2021</password>
            </server>
          </servers>

          <profiles>
            <profile>
              <id>ibm-cloud</id>
              <repositories>
                <repository>
                  <id>nexus3-releases</id>
                  <name>Nexus3 releases</name>
                  <url>http://nexus3.tools.svc:80/repository/maven-releases/</url>
                </repository>
                <repository>
                  <id>nexus3-snapshots</id>
                  <name>Nexus3 snapshots</name>
                  <url>http://nexus3.tools.svc:80/repository/maven-snapshots/</url>
                </repository>                
              </repositories>
            </profile>
          </profiles>
          
          <activeProfiles>
            <activeProfile>ibm-cloud</activeProfile>
          </activeProfiles>

          <mirrors>
            <mirror>
              <id>mirror.default</id>
              <url>http://nexus3.tools.svc:80/repository/maven-central/</url>
              <mirrorOf>central</mirrorOf>
            </mirror>
          </mirrors>
        </settings>

        EOF

        cat $(workspaces.maven-settings.path)/settings.xml 
    - name: mvn-goals
      args:
        - '-s'
        - $(workspaces.maven-settings.path)/settings.xml
        - -Dmaven.repo.local=$(workspaces.maven-repo.path)
        - -e
        - $(params.GOALS)
      command:
        - /usr/bin/mvn
      image: image-registry.openshift-image-registry.svc.cluster.local:5000/tools-images/mvn:for-use
      resources: {}
      workingDir: $(workspaces.source.path)/$(params.git-repo-checkout-dir)/$(params.pom-dir)  
  workspaces:
    - name: source
    - name: maven-settings
    - name: maven-repo
