apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: aot-mockup
spec:
  steps:
    - name: place-holder 
      image: image-registry.openshift-image-registry.svc.cluster.local:5000/tools-images/ubi-minimal:for-use
      resources: {}
      script: |
        #!/usr/bin/env bash
        echo "mock-up"