apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: aot-maven-settings
spec:
  params:
    - default: ''
      description: The Maven repository mirror url
      name: MAVEN_MIRROR_URL
      type: string
    - default: ''
      description: The username for the proxy server
      name: PROXY_USER
      type: string
    - default: ''
      description: The password for the proxy server
      name: PROXY_PASSWORD
      type: string
    - default: ''
      description: Port number for the proxy server
      name: PROXY_PORT
      type: string
    - default: ''
      description: Proxy server Host
      name: PROXY_HOST
      type: string
    - default: ''
      description: Non proxy server host
      name: PROXY_NON_PROXY_HOSTS
      type: string
    - default: http
      description: Protocol for the proxy ie http or https
      name: PROXY_PROTOCOL
      type: string
  steps:
    - image: 'registry.access.redhat.com/ubi8/ubi-minimal:latest'
      name: mvn-settings
      resources: {}
      script: >
        #!/usr/bin/env bash

        echo 'Generated $(workspaces.maven-settings.path)/settings.xml:' 

        rm -f $(workspaces.maven-settings.path)/settings.xml 

        cat > $(workspaces.maven-settings.path)/settings.xml <<EOF

        <settings>
          
          <servers>
            <server> 
              <id>releases-repository</id> 
              <username>admin</username> 
              <password>admin123</password>
            </server> 
            <server> 
              <id>snapshots-repository</id> 
              <username>admin</username> 
              <password>admin123</password>
            </server> 
            <server> 
              <id>mirror.default</id> 
              <username>kitty-catt</username> 
              <password>climbs-the-wall</password>
            </server>
            <server>
                <id>silver-platter</id>
                <username>aot-user</username>
                <password>ibm-prevail-2021</password>
            </server>                                
          </servers>
          
          <mirrors>
            <!-- The mirrors added here are generated from environment variables. Don't change. -->
            <!-- ### mirrors from ENV ### -->
          </mirrors>
          <proxies>
            <!-- The proxies added here are generated from environment variables. Don't change. -->
            <!-- ### HTTP proxy from ENV ### -->
          </proxies>
        </settings>

        EOF


        xml=""

        if [ -n "$(params.PROXY_HOST)" -a -n "$(params.PROXY_PORT)" ]; then
          xml="<proxy>\
            <id>genproxy</id>\
            <active>true</active>\
            <protocol>$(params.PROXY_PROTOCOL)</protocol>\
            <host>$(params.PROXY_HOST)</host>\
            <port>$(params.PROXY_PORT)</port>"
          if [ -n "$(params.PROXY_USER)" -a -n "$(params.PROXY_PASSWORD)" ]; then
            xml="$xml\
                <username>$(params.PROXY_USER)</username>\
                <password>$(params.PROXY_PASSWORD)</password>"
          fi
          if [ -n "$(params.PROXY_NON_PROXY_HOSTS)" ]; then
            xml="$xml\
                <nonProxyHosts>$(params.PROXY_NON_PROXY_HOSTS)</nonProxyHosts>"
          fi
          xml="$xml\
              </proxy>"
          sed -i "s|<!-- ### HTTP proxy from ENV ### -->|$xml|" $(workspaces.maven-settings.path)/settings.xml
        fi


        if [ -n "$(params.MAVEN_MIRROR_URL)" ]; then
          xml="    <mirror>\
            <id>mirror.default</id>\
            <url>$(params.MAVEN_MIRROR_URL)</url>\
            <mirrorOf>central</mirrorOf>\
          </mirror>"
          sed -i "s|<!-- ### mirrors from ENV ### -->|$xml|" $(workspaces.maven-settings.path)/settings.xml
        fi


        [[ -f $(workspaces.maven-settings.path)/settings.xml ]] && cat
        $(workspaces.maven-settings.path)/settings.xml

        [[ -f $(workspaces.maven-settings.path)/settings.xml ]] || echo skipping
        settings
  workspaces:
    - name: maven-settings

